# Generated by Django 5.0.4 on 2024-05-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotless', '0002_remove_user_name_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='lol', max_length=70),
            preserve_default=False,
        ),
    ]
