# Generated by Django 5.0.4 on 2024-12-10 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotless', '0005_remove_cleaningschedule_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaningschedule',
            name='cleaner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
