# Generated by Django 5.0.4 on 2024-12-13 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotless', '0007_cleaningchecklist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cleaningschedule',
            old_name='cleaner',
            new_name='cleaners',
        ),
    ]
