# Generated by Django 5.0.4 on 2024-12-13 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotless', '0008_rename_cleaner_cleaningschedule_cleaners'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningschedule',
            name='cleaning_checklist',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='spotless.cleaningchecklist'),
            preserve_default=False,
        ),
    ]
