# Generated by Django 5.0.4 on 2024-12-13 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotless', '0010_rename_template_image_cleaningchecklistitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaningcheckliststepimages',
            name='cleaning_checklist_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='spotless.cleaningcheckliststep'),
        ),
    ]
