# Generated by Django 5.0.4 on 2024-12-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotless', '0012_cleaningcheckliststepimages_cleanliness_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaningcheckliststepimages',
            name='cleanliness_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
